name: Deploy to Server on Release

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
      cd SpringTest1/demo
      mvn clean package -DskipTests

    - name: Copy JAR to server via SCP
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        USER: ${{ secrets.SERVER_USER }}
        HOST: ${{ secrets.SERVER_HOST }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        scp -i private_key.pem -o StrictHostKeyChecking=no \
        target/*.jar $USER@$HOST:/home/$USER/app/demo.jar

    - name: Restart app on server
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        USER: ${{ secrets.SERVER_USER }}
        HOST: ${{ secrets.SERVER_HOST }}
      run: |
        ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST "sudo systemctl restart demo.service"
