name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven Repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          cd SpringTest1/demo
          mvn clean package -DskipTests

      - name: Debug Build Output
        run: |
          echo "Checking the build output directory:"
          ls -R SpringTest1/demo/target

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: SpringTest1/demo/target/*.jar

      - name: Debug Artifact Upload
        run: echo "Artifact 'application-jar' uploaded successfully."

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: application-jar

      - name: Debug Artifact Download
        run: echo "Downloading artifact"

      - name: Debug Downloaded Artifact
        run: |
          echo "Checking the downloaded artifact directory:"
          ls -R application-jar

      - name: Deploy JAR to Server
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: $ {{ secrets.DEPLOY_PATH }}
        run: |
          echo "Transferring JAR to the server..."
          scp application-jar/*.jar $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
          echo "Running the JAR on the server..."
          ssh $DEPLOY_USER@$DEPLOY_SERVER "java -jar $DEPLOY_PATH/$(ls -t $DEPLOY_PATH/*.jar | head -n 1)"
